- blocknum: 0
  session: 0
  desc: "Default Value before any hardfork"
  committee:
      electionScheme: "TopKCandidates"
      electVersion: ""
      expectedCommSize: 4
      minBidderStake: 1E+23
      minCommitteeSize: 1
      minGasBidPrice: 1E+7
      switchInterval: 5
      auctionStakeThreshold: 500000000000000000000000
      verifyBid: false
      voteCountingScheme: "Seat"
      proposerList: ""
      rewardScheme: "thunderella"
      vaultGasUnlimited: false
      rewardRatio: 50
  evm:
    version: ""
  protocol:
    blockGasLimit: 1E+8
    maxCodeSize: 24576
    gasTable: ""
    baseFee: 0
    inflation: 0
  vault:
    burnReward: false
  trustedRNG:
    rngActive: false
    version: "v1"
  consensus:
    infoInHeader: false
    k: 1
  pala:
    hardfork: false
  election:
    stopBlockSessionOffset: 25
  precompiled:
    blockSnGetterActive: false
    vaultVersion: ""
    revertDelegateCall: false
  test:
    blockchain:
      # Used to not trigger the reconfiguration during some tests.
      bigStopBlockOffset: 10000

- blocknum: 1
  desc: "Pala hardfork"
  pala:
    hardfork: true

- blocknum: 5
  desc: "Trusted RNG hardfork"
  trustedRNG:
    rngActive: true

- session: 3
  committee:
    verifyBid: true
    voteCountingScheme: "Stake"
  protocol:
    maxCodeSize: 40960
  vault:
    burnReward: false

- session: 4
  committee:
    rewardScheme: "pala-r2.1"
    vaultGasUnlimited: true
  protocol:
      gasTable: "pala-r2.1"

- session: 5
  consensus:
    infoInHeader: true
  trustedRNG:
    version: "v3"

- session: 6
  evm:
    version: "london"

- session: 7
  precompiled:
    blockSnGetterActive: true
  consensus:
    k: 3
  protocol:
    baseFee: 1e+10 # 10gwei
    inflation: 15e+18
  committee:
    rewardRatio: 90
    rewardScheme: "inflation"

- session: 8
  precompiled:
    vaultVersion: "r3"
    revertDelegateCall: true
  committee:
    electVersion: "r3"
  trustedRNG:
    version: "v4"